;This script generates a random permutatation of elents of a list
(define (rndperm lis)
  (rndsel lis (length lis))
  )
(define (rndsel lis n)
  (cond ((null? lis) lis)
	((= n 0) '())
	((< n (length lis)) (rndsel (foo lis (random (length lis))) (- n 1)))
	(else lis)
	)
  )
(define (foo lis n)
  (cond ((= n 0) (lis))
	((= n 1) (cdr lis))
	(else (cons (car lis) (foo (cdr lis) (- n 1))))
	)
  )
