;This script extracts a given no. of randomly selected elements from a list;
(define (rndsel lis n)
  (cond ((null? lis) lis)
	((= n 0) '())
	((< n (length lis)) (rndsel (foo lis (random (length lis)))  n))
	(else lis)
	)
  )
(define (foo lis n)
  (cond ((= n 0) lis)
        ((= n 1) (cdr lis))
	(else (cons (car lis) (foo (cdr lis) (- n 1))))
	)
  )
